# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='message',
            field=models.CharField(max_length=5000),
        ),
    ]
